preconnect:
  - https://gcore.jsdelivr.net
  - https://unpkg.com
  - https://cdn.bootcdn.net

inject:
  head:
    - <link rel="apple-touch-icon" sizes="180x180" href="/assets/xaoxuu/favicon/apple-touch-icon.png">
    - <link rel="icon" type="image/png" sizes="32x32" href="/assets/xaoxuu/favicon/favicon-32x32.png">
    - <link rel="icon" type="image/png" sizes="16x16" href="/assets/xaoxuu/favicon/favicon-16x16.png">
    - <link rel="manifest" href="/assets/xaoxuu/favicon/site.webmanifest">
    - <link rel="shortcut icon" href="/assets/xaoxuu/favicon/favicon.ico">
    - <meta name="theme-color" content="#f8f8f8">
    - <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" media="all" />

logo:
  icon: /assets/avatar.png
  title: Pcpa’s World
  subtitle: 'Welcome | 欢迎'


menubar:
  items: 
    - id: post
      theme: '#1BCDFC'
      title: Posts
      url: /
    - id: explore
      theme: '#FA6400'
      title: Explore
      url: /explore/
    - id: social
      theme: '#F44336'
      title: About
      url: /about/

site_tree:
  home:
    leftbar: recent
    rightbar: my_welcome
  index_blog:
    sidebar: starter, welcome, related_pages
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic


article:
  share: [wechat, link]


style:
  text-align: justify
  smooth_scroll: false
  codeblock:
    scrollbar: 0px
  font-size:
    body: 1rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"LXGW WenKai Screen", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'

plugins:
  katex:
    enable: true
    inject: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/katex.min.css" integrity="sha384-//SZkxyB7axjCAopkAL1E1rve+ZSPKapD89Lo/lLhcsXR+zOYl5z6zJZEFXil+q0" crossorigin="anonymous">